# Lab 00 - A - Data Analysis In Python - First Steps

Machine learning and data analysis (that is usually also a pre-step for learning) deal with data. Thererefore we need tools to manipulate it and extract the information we want. In the Python environment there are two very useful packages for this: [`numpy`](https://numpy.org/doc/1.19/) and [`pandas`](https://pandas.pydata.org/docs/reference/index.html#api).

In this lab, we will take the first steps into using these packages and see some of their functionalities. These will be needed throughout the course. Both packages contain many useful functionalities, of which we will introduce only a few. To find out more about the other functionalities, the documentations, **Google** and **StackOverflow** are your best friends. 

In [1]:
# Load commonly used imports (such as numpy and pandas) and several utils functions that 
# are used thoughout different labs and code examples

import sys
sys.path.append("../")
from utils import *

# Numpy - The Basics

Let us start with numpy. This package supports vector, matrix and tensor operations over numerical (but not just) data. It is very comfortable and much faster than `for` loops and classic `list` manipulations.

## Array Creation

There are multiple ways to create an array. We can create it from an existing list, load it from a file or generate a new array.


In [2]:
array_1D = np.array([6, 2, 8, 4, 5, 10, 7, 143, 9, 10])
print(array_1D)
print(array_1D.shape)

[  6   2   8   4   5  10   7 143   9  10]
(10,)


In [3]:
array_2D = np.array(
    [[10, 20, 30, 40], 
     [100, 200, 300, 400], 
     [1000, 2000, 3000, 4000]])
print(array_2D)
print(array_2D.shape)

[[  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]
(3, 4)


In [4]:
array_3D = np.array(
    [[[10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]],
    [[11, 21, 31, 41], [101, 201, 301, 401], [1001, 2001, 3001, 4001]]])
print(array_3D)
print(array_3D.shape)

[[[  10   20   30   40]
  [ 100  200  300  400]
  [1000 2000 3000 4000]]

 [[  11   21   31   41]
  [ 101  201  301  401]
  [1001 2001 3001 4001]]]
(2, 3, 4)


Using `numpy`'s functions for creating new arrays requires specifying the shape of the desired output array. This is an n-array tuple specifying the sizes of the different dimensions. 

*   Specifying the shape `(3)` will create a 1D array with 3 entries.
*   Specifying the shape `(10, 3)` will create a 2D matrix with 10 rows and 3 columns.
*   Specifying the shape `(10, 28, 28)` will create a 3D matrix (a tensor) which we can think of in the following manner: it is an object holding 10 2D matrices of size 28x28.





In [5]:
# Initalize arrays with built-in numpy functions
zeros_3D = np.zeros((4, 5, 2)) # Create a 3D arrays of 0's
ones_2D = np.ones((4, 5)) # Create a 2D arrays of 1's
print(zeros_3D)
print(ones_2D)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
np.arange(50) # Create the vector [0, 1, 2, 3, 4, .. , 48, 49]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
# Create a vector of random integers from 5 to 50, with shape (2, 3)
np.random.randint(5, 50, (2, 3))

array([[32, 23, 34],
       [30, 43, 37]])

There are many other functions such as `np.full`, `np.eye`, `np.random.uniform`, etc. Next, let us load an existsing dataset into a numpy array. This specific dataset represents images.

In [7]:
img_array = np.loadtxt(open("../datasets/MNIST_Images.csv", "rb"), delimiter=",").reshape(-1, 28, 28)
img_array.shape

(100, 28, 28)

In [9]:
px.imshow(img_array[1]).show()

## Array indexing and slicing

A great strength of `numpy` is the ease in subsetting an array to retrieve only specific parts of it. We do so by indexing and slicing the arrays. For 1D arrays these operations are very similar to those over lists.  For arrays of higher dimensions, we use a comma to separate the slicing of each dimension. For example, accessing an element in the array `arr` in the first row and second column is done by: `arr[0, 1]` (recall indexing in python begins from zero). To select only the second column, over all rows write: `arr[:, 2]`

In [10]:
array_1D = np.array([10, 11, 12, 13, 14, 15, 16])
# Select 1st element
print("Select 1st element") 
print(array_1D[1])

# Select all the elements from 1st to 4th element
print("\nSelect all the elements from 1st to 4th element") 
print(array_1D[1:5])

# Select elements [1, 4]
print("\nSelect elements [1, 4]")
print(array_1D[[1, 4]])


array_2D = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16],
                     [17, 18, 19, 20]])
# Select 1st row, 2nd column  
print(array_2D[1, 2])


randint_2D = np.random.randint(5, 50, (10, 20))
print("\nPrint random array")
print(randint_2D)

# Select from 3rd row to 5th, all the columns
print("\nSelect from 3rd row to 5th, all the columns")
print(randint_2D[2:5, :])

# Select from 3rd row to 5th, columns 1 and 2
print("\nSelect from 3rd row to 5th, columns 1 and 2")
print(randint_2D[2:5, 1:3])

# Select from 3d row to 5th, columns 3, 5, 6, and  11
print("\nSelect from 3rd row to 5th, columns 3, 5, 6, and  11")
print(randint_2D[2:5, [3, 5, 6, 11]])


Select 1st element
11

Select all the elements from 1st to 4th element
[11 12 13 14]

Select elements [1, 4]
[11 14]
7

Print random array
[[ 7  8 18 31  8 45 43 17 36 36 14  6 22 35 27 27 32 15  5 11]
 [45 45 36 37 32 22 37  7 28 38 49 32 17  6 20 12 20 30 43 41]
 [38 11 46 28 42  7 16  7 28 21 25 21 16 45 21 18 41 25 26 43]
 [39 48 42 41 18 36 33 45 46 47 16 35 25 24 29 15 29 17 13 43]
 [20 34 26 41 49 43 35 18 33 43 48 43  5 13  9  9 15 44 13 33]
 [34 42 17 47 41 47 17 38 23 48 15 35 22 11 41 15 38 37 30  9]
 [27 44 42 24 15 44 15 19 10 16 39 21 46 40 38 21 38 10 49 47]
 [41 37 41 46 23 20  8 16 26 47  6 10 17  5 21 31 28 37 45 18]
 [28 45 22 24 37 32 47  7 22 21 41 34 41 11 41 19 41 44 18 32]
 [24 49 43 34 13 24 47 27 31 40 30 46 40 14 36  6 33 31 48 48]]

Select from 3rd row to 5th, all the columns
[[38 11 46 28 42  7 16  7 28 21 25 21 16 45 21 18 41 25 26 43]
 [39 48 42 41 18 36 33 45 46 47 16 35 25 24 29 15 29 17 13 43]
 [20 34 26 41 49 43 35 18 33 43 48 43  5 13  9  9 15 44 13 

## Matrix Operations
Another strength of the `numpy` package is that all matrix operations you can think of (and even more) are already implemented. For example, element-wise addition of scalar, multiplication, powering up a matrix, log-transformations and much more.

As `numpy` overloads the different mathematical operators, it is easy to write mathematical expressions over 2 (or more) vectors/matrices, such as summing or multiplying and also comparing their elements.


In [12]:
# Operations on 1 matrix
A = np.arange(1, 33).reshape(4, 8) # Create an array of numbers from 1 ot 32, and then make a 2d array of 4 rows to 8 columns
print(A)

print("\n\nA + 1:")
print(A + 1)
print("\n2 * A:")
print(2 * A)
print("\nA*A*A:")
print(np.power(A, 3))
print("\nlog(A):")
print(np.log(A))
print("\nA Transpose:")
print(A.transpose) # also np.transpose(A) and A.T are valid syntaxes
print("\n A > 10:")
print(A > 10)

# Operations on 2 matrices
A = np.arange(6).reshape([2, 3])
B = np.random.randint(1, 10, (2, 3))
print("A")
print(A)
print("\n\nB")
print(B)

print("\nA+B:")
print(A + B) # Equivalent to np.add(a_array, b_array)
print("\n A * B (element-wise multiplication):")
print(np.multiply(A, B))
print("\n AB (matrix multiplication):")
print(A @ B.T) # Equivalent to np.dot(a_array, b_array)

print("\nA > B")
print(A > B)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


A + 1:
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]]

2 * A:
[[ 2  4  6  8 10 12 14 16]
 [18 20 22 24 26 28 30 32]
 [34 36 38 40 42 44 46 48]
 [50 52 54 56 58 60 62 64]]

A*A*A:
[[    1     8    27    64   125   216   343   512]
 [  729  1000  1331  1728  2197  2744  3375  4096]
 [ 4913  5832  6859  8000  9261 10648 12167 13824]
 [15625 17576 19683 21952 24389 27000 29791 32768]]

log(A):
[[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
  1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665 2.56494936 2.63905733
  2.7080502  2.77258872]
 [2.83321334 2.89037176 2.94443898 2.99573227 3.04452244 3.09104245
  3.13549422 3.17805383]
 [3.21887582 3.25809654 3.29583687 3.33220451 3.36729583 3.40119738
  3.4339872  3.4657359 ]]

A Transpose:
<built-in method transpose of numpy.ndarray obj

For many `numpy` operations we can specify the `axis` over which to perform the operation:

In [13]:
# Concatenate matrices
print("\nConcatenate 2 arrays by the rows:")
print(np.concatenate((A, B), axis = 0)) # Concatenate rows - look at the shape
print("\nConcatenate 2 arrays by the columns:")
print(np.concatenate((A, B), axis = 1)) # Concatenate columns - look at the shape




Concatenate 2 arrays by the rows:
[[0 1 2]
 [3 4 5]
 [8 4 2]
 [1 2 8]]

Concatenate 2 arrays by the columns:
[[0 1 2 8 4 2]
 [3 4 5 1 2 8]]


##  Basic Statistics

You can easily calculate a lot of basic statistics from an array, such as the sum, mean, variance, maximum, argmax, etc. All of these can be retrieved either over the entire array or over rows/columns.

For each of these functions, you can get the statistic for: 
- the whole array: `np.stat(arr)`
- by row: `np.stat(arr, axis = 1)`
- by column: `np.stat(arr, axis = 0)`

In [14]:
# Basic statistics of a matrix
A = np.arange(6).reshape([2, 3])
print("A")
print(A)

print("\n\nSum of the array")
print(np.sum(A)) # Sum all the matrix (return a scalar)
print("\nSum of the array by column")
print(np.sum(A, axis = 0)) # Sum by column (return a vector)
print("\nSum of the array by row")
print(np.sum(A, axis = 1)) # Sum by row (return a vector)

print("\nMax of each row")
print(np.max(A, axis = 1)) # Max by column (return a vector)

print("\nMax of each column")
print(np.max(A, axis = 0)) # Max by row (return a vector)

print("\nAverage of all the array")
print(np.mean(A))


A
[[0 1 2]
 [3 4 5]]


Sum of the array
15

Sum of the array by column
[3 5 7]

Sum of the array by row
[ 3 12]

Max of each row
[2 5]

Max of each column
[3 4 5]

Average of all the array
2.5


## Sampling From Distributions

`numpy` provides a broad set of distributions to sample from. We will cover this in more depth in lab 2. 

In [15]:
A = np.random.randint(1, 15, size = 20)
print("A")
print(A)

print("\n\nThe values that appear in the array")
print(np.unique(A))
print("\nHow many values are between [0, 5), [5, 10), [10, 15]")
np.histogram(A, bins = [0, 5, 10, 15])

A
[14  9  5  6 11  3  2 10 14  7  8 12 10 11  8  6  6 13 11  4]


The values that appear in the array
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]

How many values are between [0, 5), [5, 10), [10, 15]


(array([3, 8, 9]), array([ 0,  5, 10, 15]))

## Linear Algebra
One of the most important mathematical fields in machine learning is linear algebra. You can perform many of these operations using `numpy`. You can calculate the eigenvectors of a matrix, or its inverse, the rank of the matrix and so on.

In [16]:
A = np.array([[1., 2.], [3., 4.]])
print("A")
print(A)
print("\n\nInverse of A")
print(np.linalg.inv(A))

B = np.diag((1, 2, 3))
print("\n\nB")
print(B)

eigvalues, eigvectors = np.linalg.eig(B)
print("\neigenvalues, eigenvectors")
print(eigvalues, eigvectors)

print("\nRank of the matrix")
print(np.linalg.matrix_rank(B))


A
[[1. 2.]
 [3. 4.]]


Inverse of A
[[-2.   1. ]
 [ 1.5 -0.5]]


B
[[1 0 0]
 [0 2 0]
 [0 0 3]]

eigenvalues, eigenvectors
[1. 2. 3.] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Rank of the matrix
3


## Reshaping

You can change the shape of your array, with transpose, flattening, reshape, 
adding a new axis (see `np.newaxis`)



In [17]:
B = np.array([[1, 2, 3], [4, 5, 6]])

print("\n\nB")
print(B)

print("\nFlatten matrix")
print(np.ravel(B))


print("\nTranspose matrix")
print(B.transpose())



B
[[1 2 3]
 [4 5 6]]

Flatten matrix
[1 2 3 4 5 6]

Transpose matrix
[[1 4]
 [2 5]
 [3 6]]


## Sorting

You can sort the matrix by row or by column

In [18]:
B = np.array([[3, 6, 1, 4, 10], [5, 1, 8, 3, 65]])

print("B")
print(B)

print("\n\nSort by row")
print(np.sort(B, axis = 1))


B
[[ 3  6  1  4 10]
 [ 5  1  8  3 65]]


Sort by row
[[ 1  3  4  6 10]
 [ 1  3  5  8 65]]


## Indexing By Condition


In [19]:
A = np.random.randint(1, 30, (5, 4))
print("A")
print(A)

print("\nGet the numbers that are greater than 5:")
print(A[A > 5])

print("\nGet the numbers that are divisible by 4:")
print(np.extract(np.mod(A, 4)==0, A))

A
[[10 24 22  8]
 [23  2 20 14]
 [21  5 14 22]
 [18  1  3 20]
 [11 29 20 28]]

Get the numbers that are greater than 5:
[10 24 22  8 23 20 14 21 14 22 18 20 11 29 20 28]

Get the numbers that are divisible by 4:
[24  8 20 20 20 28]


## Let's practice!

To get you a bit more accustomed to `numpy` you are encouraged to solve the following challenges. If you choose to not solve the following challenges, be sure to understand the solutions. Do not use loops or list comprehensions.



Write a program to create a `7x10` matrix that has `0` and `1` staggered:
```
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
```
Hint: use slice operations on different axes.


In [22]:
res = np.zeros((7,10))
res[1::2,::2] = 1.
res[::2,1::2] = 1.
res

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [19]:
staggered = np.zeros((7, 10))
staggered[::2, 1::2] = 1
staggered[1::2, ::2] = 1

print(staggered)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


Calculate the volume of a cylinder with the following diameters and lengths:


In [20]:
diameters = np.array([1, 3, 5, 2, 4])
lengths = np.array([10, 20, 3, 10, 5])

In [21]:
print(np.array(np.power(diameters/2, 2)*lengths*np.pi))

[  7.85398163 141.37166941  58.90486225  31.41592654  62.83185307]


Write a function that receives 2 vectors and returns their cartesian product:
```
def create_cartesian_product(vec1, vec2):
  pass
```



In [27]:
def cartesian_product(vec1, vec2):
    vec1 = np.asarray(vec1)
    vec2 = np.asarray(vec2)
    return np.column_stack([np.tile(vec1.T, len(vec2)), np.repeat(vec2,len(vec1)).T])

print(cartesian_product([1, 2, 3], [4, 5, 6, 7]))

[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]
 [1 6]
 [2 6]
 [3 6]
 [1 7]
 [2 7]
 [3 7]]


In [22]:
def cartesian_product(vec1, vec2):
    # np.repeat([1, 2, 3], 4) -> [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
    # np.tile([1, 2, 3], 4)   -> [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
    return np.transpose(np.array([np.repeat(vec1, len(vec2)), np.tile(vec2, len(vec1))]))

print(cartesian_product([1, 2, 3], [4, 5, 6, 7]))

[[1 4]
 [1 5]
 [1 6]
 [1 7]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [3 4]
 [3 5]
 [3 6]
 [3 7]]


Given an array `a` and a number `n`, find the closest number to `n` in `a`:
```
def find_closest(a, n):
  pass
```



In [32]:
def find_closest(a,n):
    a = np.asarray(a)
    return a[np.argmin(np.abs(a-n))]

print(find_closest([1, 24, 12, 13, 14], 10))

12


In [23]:
def find_closest(a, n):
  a = np.array(a)
  return a[np.argmin(np.abs(a - n))]
                     
print(find_closest([1, 24, 12, 13, 14], 10))

12


Check if the sudoku grid is valid:
*   Check that each row contains all the numbers from 1 to 9
*   Check that each column contains all the numbers from 1 to 9
*   Check that each of the 9 non-overlapping `3x3` blocks composing grid contain 1 to 9

You can assume it contains only integers and that the shape of the array is `9x9`
```
def check_sudoku(grid):
  pass
```



In [ ]:
def check_sudoku(grid):
    

In [24]:
    def is_1_to_9(array_):
    # Return True if the array contains all the numbers from 1 to 9, False otherwise
        return np.all(np.sort(array_, axis = None) == np.arange(1, 10))

def check_sudoku(grid):
    def check_block(coords_block):
        return is_1_to_9(grid[coords_block[0]*3 : coords_block[0]*3+3, 
                              coords_block[1]*3 : coords_block[1]*3+3])

    grid = np.array(grid)

    # Check that the grid contains only 1 to 9
    if (not is_1_to_9(np.unique(grid))):
        return False

    # Check that each line/column contains 1 to 9:
    # Sort each column. We expect it to be
    # [[1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2] ... [9, 9, 9, 9, 9, 9, 9, 9, 9]]
    # Thus we expect the sums of the rows: 1*9, 2*9....
    if  np.any(np.sum(np.sort(grid, axis = 0), axis = 1) != np.arange(1, 10)*9):
        return False

    # Make the same for the columns
    if np.any(np.sum(np.sort(grid.transpose(), axis = 0), axis = 1) != np.arange(1, 10)*9):
        return False


    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
    #
    #
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
    #
    #
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
    # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2


    # For each block of 9, check if it contains all the numbers 1 to 9
    blocks_are_valid = np.apply_along_axis(check_block, 1, cartesian_product([0, 1, 2], [0, 1, 2]))
    return np.all(blocks_are_valid)


Given a matrix, check if some row is a scalar multplication of another
```
def check_dependencies(matrix_):
  pass
```



In [25]:
def check_dependencies(matrix_):
    def rows_are_dependent(indices):
        if indices[0] == indices[1]:
            return False
        return np.unique(matrix_[indices[0],] / matrix_[indices[1],]).shape[0] == 1

    return np.any(np.apply_along_axis(rows_are_dependent, 1,
                                      cartesian_product(np.arange(matrix_.shape[0]), np.arange(matrix_.shape[0]))))


Write a function that gets a 1D array and check if there is no local extrema point in addition to the global one.
```
def have_an_extrema(array):
  pass
```



In [26]:
def have_a_maxima(array):
    argmax_arr = np.argmax(array[1:-1]) + 1
    before_max_neg = np.all(array[:argmax_arr - 1] - array[1:argmax_arr] < 0)
    after_max_neg = np.all(array[argmax_arr:-1] - array[argmax_arr + 1:] > 0)
    return before_max_neg and after_max_neg

def have_an_extrema(array):
    # Check if it is a monotonic series
    if np.unique(array[:-1] - array[1:]).shape[0] == 1: return True

    # If there is a minimum, we can look for a maximum in the negated array
    return have_a_maxima(array) or have_a_maxima(-array)


Note that instead of `array[:argmax_arr - 1] - array[1:argmax_arr]`, you could use the `np.diff` function


# Pandas
Until now, we have only looked at numerical data. But in real-world problems, we also have textual and categorical data. To manipulate this type of data, we will use the `pandas` library. One of the basic data structures of `pandas` is called a `DataFrame`. Generally, in a `DataFrame`, each row is a different sample and each column is a feature.

For example, each row can represent a student, with columns of the ID, birthday, and gender of the student. 

`pandas` has a lot of possibilities of which we are going to introduce a very small subset.

## Array Creation

In addition to creating an array from lists or randomly generated data frames, we are going to use an existing dataset of house prices (you will get back to this dataset in excercise 2).

In [33]:
# Load https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data?select=train.csv
df = pd.read_csv('../datasets/house_train.csv', index_col=0)
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [34]:
print("\nRows Names")
print(df.index)
print("\nColumns Names")
print(df.columns)
print("\nDf train shape")
print(df.shape)


Rows Names
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460],
           dtype='int64', name='Id', length=1460)

Columns Names
Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'Bedroo

## Indexing And Slicing
Just like when using `numpy` you can select a subset of rows and columns. You can do it using indices or using names of the rows and columns. You can easily add a new column based on existing ones.

In [35]:
print("\ndf[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]")
print(df[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]) # Select  GrLivArea columns SalePrice BedroomAbvGr

print("\ndf.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ]")
print(df.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ])

print("\ndf.iloc[[3, 4, 5]]")
print(df.iloc[[3, 4, 5]])
print("\ndf.iloc[3:10,[6, 7, 8]]")
print(df.iloc[3:10,[6, 7, 8]])


df[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]
      GrLivArea  SalePrice  BedroomAbvGr
Id                                      
1          1710     208500             3
2          1262     181500             3
3          1786     223500             3
4          1717     140000             3
5          2198     250000             4
...         ...        ...           ...
1456       1647     175000             3
1457       2073     210000             3
1458       2340     266500             4
1459       1078     142125             2
1460       1256     147500             3

[1460 rows x 3 columns]

df.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ]
    GrLivArea  SalePrice  BedroomAbvGr
Id                                    
3        1786     223500             3
4        1717     140000             3
5        2198     250000             4
6        1362     143000             1
7        1694     307000             3
8        2090     200000             3
9        1774     129900

In [36]:
individual_df = pd.DataFrame(np.array([np.random.randint(2000000, 3000000,50), np.random.uniform(1.50, 1.70, size = 50), np.random.uniform(45, 90, size = 50)]).transpose(), columns=['ID','Height','Weight'])

individual_df["BMI"] = individual_df["Weight"] / individual_df["Height"].pow(2)
print("\nIndividual DF")
print(individual_df.head())


Individual DF
          ID    Height     Weight        BMI
0  2083730.0  1.509751  55.774375  24.469453
1  2514467.0  1.537939  69.426029  29.352449
2  2842917.0  1.640221  56.663613  21.061998
3  2515421.0  1.617643  56.654447  21.650543
4  2129130.0  1.558012  85.163184  35.084102


# Basic Statistics
`pandas` provides different statistical functions over `DataFrame`s.

In [31]:
print("\nMedian of the SalePrice column")
print(df.SalePrice.median())

print("\nSelecting rows by condition")
median_price = df.SalePrice.median()
print(df[df.SalePrice > median_price].head())



Median of the SalePrice column
163000.0

Selecting rows by condition
    MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   
7           20       RL         75.0    10084   Pave   NaN      Reg   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        

## Group-by

When working with data that contains also a categorical feature, we are often interested in performing some kind of calculation over all rows containing the same categorical value. For example, given a data frame of student grades for different courses, we can calculate the students' average grade.

In [32]:
students_df = pd.DataFrame(np.array([np.random.choice(["Zohar", "Shelly", "Omer", "Avi"],50), np.random.choice(["Linearit", "Intro", "Infi", "Probabilistic"], 50), np.random.randint(80, 101, 50)]).transpose(), columns=['Name','Course','Grade'])
students_df["Grade"] = students_df["Grade"].astype(int)

print("\n\nStudents df")
print(students_df.head())

print("\n\nCalculate average by student and by course")
print(students_df.groupby(['Name', 'Course']).mean().reset_index())



Students df
     Name         Course  Grade
0  Shelly  Probabilistic     89
1   Zohar          Intro     83
2  Shelly  Probabilistic     83
3   Zohar          Intro     99
4  Shelly  Probabilistic     91


Calculate average by student and by course
      Name         Course      Grade
0      Avi           Infi  83.666667
1      Avi          Intro  83.666667
2      Avi       Linearit  89.666667
3      Avi  Probabilistic  84.000000
4     Omer           Infi  90.000000
5     Omer          Intro  89.333333
6     Omer       Linearit  90.000000
7     Omer  Probabilistic  93.000000
8   Shelly           Infi  86.500000
9   Shelly          Intro  91.000000
10  Shelly       Linearit  87.750000
11  Shelly  Probabilistic  90.166667
12   Zohar           Infi  93.000000
13   Zohar          Intro  91.000000
14   Zohar       Linearit  97.000000
15   Zohar  Probabilistic  88.000000


## Sorting
As in `numpy` you can sort data frame based on a column

In [33]:
students_df.sort_values(by='Grade').head()

Name    Course  Grade
29  Shelly      Infi     80
26     Avi     Intro     81
47     Avi  Linearit     81
40     Avi      Infi     81
21    Omer     Intro     82

## Executing Functions By Columns

In `pandas`, you can select columns and apply functions to them. You also can apply functions by elements.

In [34]:
df = pd.DataFrame(np.random.randint(1, 10, (5,3)),columns=['col1','col2','col3'])

print("\n\ndf")
print(df)
print("\nCalculate the difference between the min and the max of each column")
print(df.apply(lambda x: x.max() - x.min()))

# Apply by element
print("\nMultiply elements by 100")
print(df.applymap(lambda x:x*100))

print("\n\nIterate over the columns")
print("\n-----------------------")
for key,value in df.iteritems():
   print(key,value)

print("\n\nIterate over the rows")
print("\n-----------------------")
for row_idx,row in df.iterrows():
   print(row_idx,row)



df
   col1  col2  col3
0     2     5     9
1     6     8     1
2     2     6     1
3     3     4     9
4     2     9     6

Calculate the difference between the min and the max of each column
col1    4
col2    5
col3    8
dtype: int64

Multiply elements by 100
   col1  col2  col3
0   200   500   900
1   600   800   100
2   200   600   100
3   300   400   900
4   200   900   600


Iterate over the columns

-----------------------
col1 0    2
1    6
2    2
3    3
4    2
Name: col1, dtype: int32
col2 0    5
1    8
2    6
3    4
4    9
Name: col2, dtype: int32
col3 0    9
1    1
2    1
3    9
4    6
Name: col3, dtype: int32


Iterate over the rows

-----------------------
0 col1    2
col2    5
col3    9
Name: 0, dtype: int32
1 col1    6
col2    8
col3    1
Name: 1, dtype: int32
2 col1    2
col2    6
col3    1
Name: 2, dtype: int32
3 col1    3
col2    4
col3    9
Name: 3, dtype: int32
4 col1    2
col2    9
col3    6
Name: 4, dtype: int32


## Merging Data Frames


In [35]:
# Concatenate data frames
import pandas as pd

# Create 2 data frames
ids_df1 = pd.DataFrame({
        'ID': ['336097897', '32109678', '25976389', '32438509', '36790307'],
         'name': ['Amos', 'Eran', 'Sapir', 'Amichai', 'Hadar'], 
        'gender': ["M", "M", "F", "M", "F"]})

ids_df2 = pd.DataFrame({
        'ID': ['21370565', '34256798', '3908412', '326780578'],
        'name': ['Matan', 'Gabriel', 'Anael', 'Liora'], 
        'gender': ["M", "M", "F", "F"]})

print("\n\ndf1")
print(ids_df1)
print("\ndf2")
print(ids_df2)
print("\n\nJoin the two dataframes along rows:")
concatenate_data = pd.concat([ids_df1, ids_df2])
print(concatenate_data)



df1
          ID     name gender
0  336097897     Amos      M
1   32109678     Eran      M
2   25976389    Sapir      F
3   32438509  Amichai      M
4   36790307    Hadar      F

df2
          ID     name gender
0   21370565    Matan      M
1   34256798  Gabriel      M
2    3908412    Anael      F
3  326780578    Liora      F


Join the two dataframes along rows:
          ID     name gender
0  336097897     Amos      M
1   32109678     Eran      M
2   25976389    Sapir      F
3   32438509  Amichai      M
4   36790307    Hadar      F
0   21370565    Matan      M
1   34256798  Gabriel      M
2    3908412    Anael      F
3  326780578    Liora      F


In [36]:
birthdates_id = pd.DataFrame({
        'ID': ['336097897', '32109678', '25976389', '32438509', '36790307', '21370565', '34256798', '3908412', '326780578'],
        'birth_year': [1995, 1996, 1993, 1994, 1997, 1991, 1994, 1992, 1996]})

print("\nNow join the result_data and df_exam_data along ID:")
pd.merge(concatenate_data, birthdates_id, on='ID')


Now join the result_data and df_exam_data along ID:


ID     name gender  birth_year
0  336097897     Amos      M        1995
1   32109678     Eran      M        1996
2   25976389    Sapir      F        1993
3   32438509  Amichai      M        1994
4   36790307    Hadar      F        1997
5   21370565    Matan      M        1991
6   34256798  Gabriel      M        1994
7    3908412    Anael      F        1992
8  326780578    Liora      F        1996

## Let's Practice!

Let us create a table of flight companies' flights. Each row will represent a single flight and will have 3 features: city of departure, city of destination and price. 

Implement a function `create_flight_df` that recieves a collection of cities and creates a dataset of randomly selected flights and a price in the range of 100-400.

```
    def create_flight_df(cities_poss, nrows = 100):
        pass
```

The output data frame must not have more than a single record for any pair of cities. There are no flights from a city to itself.

In [37]:
import numpy as np
import pandas as pd

def create_flight_df(cities, nrows = 20):
    df = pd.DataFrame([], columns=["Departure", "Destination", "Price"])
    
    while df.shape[0] < nrows:
        dep, dest = np.random.choice(cities, size=2, replace=False)
        price = np.random.randint(100, 400)
        
        if not ((df["Departure"] == dep) & (df["Destination"] == dest)).any():
            df = df.append({"Departure": dep, "Destination": dest, "Price": price}, ignore_index=True)
    return df

cities = ["Beijing", "Moscow", "New-York", "Tokyo", "Paris", "Cairo", "Santiago", "Lima", "Kinshasa", "Singapore", 
          "New-Delhi", "London", "Ankara", "Nairobi", "Ottawa", "Seoul", "Tehran", "Guatemala", "Caracas", "Vienna"]

flights = create_flight_df(cities)
flights.head()

Departure Destination Price
0     Seoul   Guatemala   371
1     Seoul        Lima   393
2     Cairo    Santiago   353
3     Seoul      Moscow   391
4    Tehran       Paris   275

As there are pairs of cities with no direct flight between them, let us find the pairs of cities that have a single connection flight between them and calculate the total price of the flgihts. To do so merge the two data frames. This operation is often referred to as "joining" with the options of inner, outer, left, right and cross joining. For more about merging `pandas` data frames read the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#database-style-dataframe-or-named-series-joining-merging).

In [38]:
df = pd.merge(flights, flights, left_on=["Destination"], right_on=["Departure"], how="inner")
df = df[df.Departure_x != df.Destination_y]
df["Total_Price"] = df["Price_x"] + df["Price_y"]

df.head()

Departure_x Destination_x Price_x Departure_y Destination_y Price_y  \
0       Seoul     Guatemala     371   Guatemala         Cairo     382   
2       Seoul          Lima     393        Lima         Cairo     383   
3       Seoul          Lima     393        Lima       Nairobi     271   
4     Caracas          Lima     122        Lima         Cairo     383   
5     Caracas          Lima     122        Lima       Nairobi     271   

  Total_Price  
0         753  
2         776  
3         664  
4         505  
5         393

Create a data frame with all flights of no connection and single connection.

In [39]:
flights = flights.append(df[["Departure_x", "Destination_y", "Total_Price"]]\
                         .rename(columns={"Departure_x":"Departure", "Destination_y":"Destination", "Total_Price":"Price"}))
flights

Departure Destination Price
0       Seoul   Guatemala   371
1       Seoul        Lima   393
2       Cairo    Santiago   353
3       Seoul      Moscow   391
4      Tehran       Paris   275
5   Singapore     Caracas   172
6   Guatemala       Cairo   382
7     Caracas        Lima   122
8       Cairo   New-Delhi   159
9      London      Moscow   152
10    Nairobi      Moscow   236
11      Cairo      Moscow   129
12     Ankara    Kinshasa   396
13       Lima       Cairo   383
14    Beijing       Cairo   131
15     Ankara       Seoul   351
16  Guatemala       Seoul   292
17  Singapore      Vienna   257
18    Nairobi       Seoul   180
19       Lima     Nairobi   271
0       Seoul       Cairo   753
2       Seoul       Cairo   776
3       Seoul     Nairobi   664
4     Caracas       Cairo   505
5     Caracas     Nairobi   393
6   Singapore        Lima   294
7   Guatemala    Santiago   735
8   Guatemala   New-Delhi   541
9   Guatemala      Moscow   511
10       Lima    Santiago   736
11       Lima   New-Delhi   542
12       Lima      Moscow   512
13    Beijing    Santiago   484
14    Beijing   New-Delhi   290
15    Beijing      Moscow   260
16     Ankara   Guatemala   722
17     Ankara        Lima   744
18     Ankara      Moscow   742
20  Guatemala        Lima   685
21  Guatemala      Moscow   683
22    Nairobi   Guatemala   551
23    Nairobi        Lima   573
24    Nairobi      Moscow   571
25       Lima      Moscow   507
26       Lima       Seoul   451

Since now we might have more than one way to flight between each pair of cities, let us find the cheapest flight option, with one connection, between two cities.

In [40]:
min_by_group = df.groupby(["Departure_x", "Destination_y"], as_index=False)["Total_Price"].min()
min_by_group

Departure_x Destination_y  Total_Price
0       Ankara     Guatemala          722
1       Ankara          Lima          744
2       Ankara        Moscow          742
3      Beijing        Moscow          260
4      Beijing     New-Delhi          290
5      Beijing      Santiago          484
6      Caracas         Cairo          505
7      Caracas       Nairobi          393
8    Guatemala          Lima          685
9    Guatemala        Moscow          511
10   Guatemala     New-Delhi          541
11   Guatemala      Santiago          735
12        Lima        Moscow          507
13        Lima     New-Delhi          542
14        Lima      Santiago          736
15        Lima         Seoul          451
16     Nairobi     Guatemala          551
17     Nairobi          Lima          573
18     Nairobi        Moscow          571
19       Seoul         Cairo          753
20       Seoul       Nairobi          664
21   Singapore          Lima          294

And if we want to know on average what is the most expensive city to fly to then:

In [41]:
mean_by_dest = min_by_group.groupby("Destination_y")["Total_Price"].mean()
expensive_city = mean_by_dest.idxmax()
expensive_city

'Santiago'